export default {
  '[data-prefers-color=dark]': {
    'color-scheme': 'dark',
    primary: 'indigo-500',
    success: 'green-400',
    warning: 'yellow-400',
    error: 'red-400',
    info: 'blue-400',
    'neutral-text': 'white',
    'neutral-border': 'white/20',
    'neutral-fill': 'gray-100',
    'neutral-fill-secondary': 'white/12',
    'neutral-bg-container': 'black/10',
    'neutral-bg-elevated': 'white',
    'neutral-bg-layout': 'gray-100',
    'neutral-bg-spotlight': 'gray-900',
    'neutral-bg-mask': 'gray-500',
  },
  '[data-prefers-color=light]': {
    'color-scheme': 'light',
    primary: 'indigo-600',
    success: 'green-500',
    warning: 'yellow-500',
    error: 'red-500',
    info: 'blue-500',
    'neutral-text': 'gray-900',
    'neutral-border': 'gray-300',
    'neutral-fill': 'gray-300',
    'neutral-bg-container': 'white',
    'neutral-bg-elevated': 'white',
    'neutral-bg-layout': 'slate-100',
    'neutral-bg-spotlight': 'gray-900',
    'neutral-bg-mask': 'gray-500',
  },
} as const;
